### ISSUE TITLE
Alerts seems to be always Empty

### ISSUE THREAD

**Issue by rraina8** [noanadler/RockStars#10]
I tried selecting 30 odd countries, but nothing showed up on the Alerts section. Want to make sure that this functionality is working correctly.

**Comment by jgadbois** [comment]
Try syria

**Comment by rraina8** [comment]
Still nothing. Added Syria separately as well as in a list but Alerts is empty.

**Comment by jgadbois** [comment]
That was definitely working.  I'll check later to make sure the alerts table is still populated.  I wonder if our job cleared it out

Sent from Outlook Mobile

On Sat, Apr 16, 2016 at 10:19 AM -0700, "rraina8" notifications@github.com wrote:

Still nothing. Added Syria separately as well as in a list but Alerts is empty.

**Comment by jgadbois** [comment]
@noanadler @rraina8 This is fixed and deploying later tonight.  Previously alerts where referenced by country name, now it's by country id, so i updated the code accordingly  cc/ @forrestbrazeal
