### ISSUE TITLE
Logic error in Registrator.isRegistrationExpired

### ISSUE THREAD

**Issue by noanadler** [noanadler/RockStars#3]
The following code:
User user1 = _model.getUserByUid(uId);
user1.setRegistered_at(someDate);
User user2 = _model.getUserByUid(uId);
Date registered = user2.getRegistered_at();
return registered;

will always return today's date (Even if someDate is not today's date).
Is this expected behavior? I would expect it to return someDate. For that reason Registrator.isRegistrationExpired always returns false even when someDate is more then a year ago

@eddiefl @jgadbois

**Comment by eddiefl** [comment]
Hi Noa,

The method updateUser does not update the registered_at field. Can you think of a valid use case where it should? The way I see it we need to set it only when the user is created.

It's  not the best practice, but I would test isRegistrationExpired by tweaking the user creation date in the db to more than 24 hours ahead,and then check the answer.

Thanks!

Eddie
