### ISSUE TITLE
Error when trying to register

### ISSUE THREAD

**Issue by noanadler** [noanadler/RockStars#4]
I filled out the email, password and name fields, clicked register and got an error.
Tried in Chrome and Safari
See attached screenshot:
(https://cloud.githubusercontent.com/assets/13839410/14569469/d2aece72-02f3-11e6-9cf7-718b9c79efc1.png)

**Comment by rraina8** [comment]
I get the same registration error as Noa.

Ravi

**Comment by jgadbois** [comment]
I wonder if FHIR is down

**Comment by jgadbois** [comment]
@noanadler I just made sure latest code was deployed and appears to be working now - if works for you, you can close this issue.

I think it wasn't the latest Java code

**Comment by noanadler** [comment]
Works!
