### ISSUE TITLE
Certain passwords break the update user query

### ISSUE THREAD

**Issue by jgadbois** [noanadler/RockStars#5]
Try password `johnjohn`  @forrestbrazeal

**Comment by forrestbrazeal** [comment]
Confirmed. Password "testtest" works fine, so it's not a length issue.

**Comment by jgadbois** [comment]
@forrestbrazeal it's some kind of utf error when trying to store the hashed password in the database.

**Comment by jgadbois** [comment]
@forrestbrazeal deploying a potential fix - please let me know if you think this is working

@rraina8 @noanadler @eddiefl this may break your existing passwords - let me know if you need to reset your accounts.
